2018-04-13 20:28:36,647 ERROR: Exception on /register [GET] [in /home/frosty/microblog/venv/local/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/frosty/microblog/app/routes.py", line 52, in register
    form = RegistrationForm()
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() takes at least 2 arguments (1 given)
2018-04-13 20:33:29,973 INFO: Microblog startup [in /home/frosty/microblog/app/__init__.py:40]
2018-04-13 20:33:46,853 ERROR: Exception on /register [POST] [in /home/frosty/microblog/venv/local/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/frosty/microblog/app/routes.py", line 53, in register
    if form.validate_on_submit():
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/wtforms/fields/core.py", line 204, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/wtforms/fields/core.py", line 224, in _run_validation_chain
    validator(form, self)
  File "/home/frosty/microblog/app/forms.py", line 30, in validate_username
    if username.data != self.original_username:
AttributeError: 'RegistrationForm' object has no attribute 'original_username'
2018-04-13 20:37:00,970 INFO: Microblog startup [in /home/frosty/microblog/app/__init__.py:40]
2018-04-13 20:37:05,265 ERROR: Exception on /register [POST] [in /home/frosty/microblog/venv/local/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/frosty/microblog/app/routes.py", line 53, in register
    if form.validate_on_submit():
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/wtforms/fields/core.py", line 204, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/frosty/microblog/venv/local/lib/python2.7/site-packages/wtforms/fields/core.py", line 224, in _run_validation_chain
    validator(form, self)
  File "/home/frosty/microblog/app/forms.py", line 26, in validate_username
    if username.data != self.original_username:
AttributeError: 'RegistrationForm' object has no attribute 'original_username'
2018-04-13 20:40:13,940 INFO: Microblog startup [in /home/frosty/microblog/app/__init__.py:40]
2018-04-13 20:43:19,931 INFO: Microblog startup [in /home/frosty/microblog/app/__init__.py:40]
